export const LIKERT = [
  { value: 1, label: "Strongly Disagree" },
  { value: 2, label: "Disagree" },
  { value: 3, label: "Neutral" },
  { value: 4, label: "Agree" },
  { value: 5, label: "Strongly Agree" },
];

export const FIELD_ORDER = [
  "TEACHER_TO_STUDENT",
  "TRADITIONAL_TO_PROCESS",
  "BEHAVIORISM_TO_CONSTRUCTIVISM",
  "COGNITIVISM_TO_SOCIAL_CONSTRUCTIVISM",
  "DIRECT_TO_EXPERIENTIAL",
  "CONSTRUCTIVISM_INDEX",
];

export const FIELD_LABELS = {
  TEACHER_TO_STUDENT: "Teacher-Centered ↔ Student-Centered",
  TRADITIONAL_TO_PROCESS: "Current Traditional Paradigm ↔ Process pedagogy (writing)",
  BEHAVIORISM_TO_CONSTRUCTIVISM: "Behaviorism ↔ Constructivism",
  COGNITIVISM_TO_SOCIAL_CONSTRUCTIVISM: "Cognitivism ↔ Social Constructivism",
  DIRECT_TO_EXPERIENTIAL: "Direct Instruction ↔ Experiential Learning",
  CONSTRUCTIVISM_INDEX: "Constructivism (index)",
};

export const SHORT_FIELD_LABELS = {
  TEACHER_TO_STUDENT: "Teacher → Student",
  TRADITIONAL_TO_PROCESS: "Traditional → Process",
  BEHAVIORISM_TO_CONSTRUCTIVISM: "Behaviorism → Constructivism",
  COGNITIVISM_TO_SOCIAL_CONSTRUCTIVISM: "Cognitivism → Social",
  DIRECT_TO_EXPERIENTIAL: "Direct → Experiential",
  CONSTRUCTIVISM_INDEX: "Constructivism",
};

export const SPECTRUM_POLES = {
  TEACHER_TO_STUDENT: { low: "Teacher-centered", high: "Student-centered" },
  TRADITIONAL_TO_PROCESS: { low: "Current Traditional Paradigm", high: "Process pedagogy" },
  BEHAVIORISM_TO_CONSTRUCTIVISM: { low: "Behaviorism", high: "Constructivism" },
  COGNITIVISM_TO_SOCIAL_CONSTRUCTIVISM: { low: "Cognitivism", high: "Social constructivism" },
  DIRECT_TO_EXPERIENTIAL: { low: "Direct instruction", high: "Experiential learning" },
  CONSTRUCTIVISM_INDEX: { low: "Less constructivist", high: "More constructivist" },
};

export const INSTRUMENT_FRAMEWORK =
  "Rate each prompt from 1–5. Six spectrums; higher scores align with student-centered, constructivist, social, experiential, and process-oriented writing pedagogy. Traditional ↔ Process contrasts product/single-draft composition with process pedagogy (drafting, revision, invention). Results: 1–100 scale.";

/** @type {Array<{id:number,stem:string,spectrum:keyof typeof FIELD_LABELS,spectrum_label:string,reverse_scored:boolean,contributes_to_constructivism:boolean}>} */
export const QUESTIONS = [
  {
    id: 1,
    stem: "In a typical week, how often do students make meaningful choices about topic, process, or product (with clear success criteria)?",
    spectrum: "TEACHER_TO_STUDENT",
    spectrum_label: FIELD_LABELS.TEACHER_TO_STUDENT,
    reverse_scored: false,
    contributes_to_constructivism: true,
  },
  {
    id: 2,
    stem: "How often do you begin a lesson/unit by telling students exactly what to do step-by-step for most of the time?",
    spectrum: "TEACHER_TO_STUDENT",
    spectrum_label: FIELD_LABELS.TEACHER_TO_STUDENT,
    reverse_scored: true,
    contributes_to_constructivism: false,
  },
  {
    id: 3,
    stem: "When a student is stuck, how often do you ask a question that helps them generate the next step before you give the answer?",
    spectrum: "TEACHER_TO_STUDENT",
    spectrum_label: FIELD_LABELS.TEACHER_TO_STUDENT,
    reverse_scored: false,
    contributes_to_constructivism: true,
  },
  {
    id: 4,
    stem: "How often do you adjust pacing, groupings, or scaffolds based on quick evidence of learning (not just a plan)?",
    spectrum: "TEACHER_TO_STUDENT",
    spectrum_label: FIELD_LABELS.TEACHER_TO_STUDENT,
    reverse_scored: false,
    contributes_to_constructivism: false,
  },
  {
    id: 5,
    stem: "How often do students move through multiple drafts of a piece of writing, with meaningful revision between drafts?",
    spectrum: "TRADITIONAL_TO_PROCESS",
    spectrum_label: FIELD_LABELS.TRADITIONAL_TO_PROCESS,
    reverse_scored: false,
    contributes_to_constructivism: true,
  },
  {
    id: 6,
    stem: "How often do you respond to drafts in progress (conference, comment, workshop) rather than only grading a final product?",
    spectrum: "TRADITIONAL_TO_PROCESS",
    spectrum_label: FIELD_LABELS.TRADITIONAL_TO_PROCESS,
    reverse_scored: false,
    contributes_to_constructivism: false,
  },
  {
    id: 7,
    stem: "How often is a writing grade based mainly on a single submitted draft with little or no revision cycle?",
    spectrum: "TRADITIONAL_TO_PROCESS",
    spectrum_label: FIELD_LABELS.TRADITIONAL_TO_PROCESS,
    reverse_scored: true,
    contributes_to_constructivism: false,
  },
  {
    id: 8,
    stem: "How often do students spend class time on invention, exploration, or discovery before a fixed form is required?",
    spectrum: "TRADITIONAL_TO_PROCESS",
    spectrum_label: FIELD_LABELS.TRADITIONAL_TO_PROCESS,
    reverse_scored: false,
    contributes_to_constructivism: true,
  },
  {
    id: 9,
    stem: "How often do students revise work based on feedback and submit a second (or third) version?",
    spectrum: "BEHAVIORISM_TO_CONSTRUCTIVISM",
    spectrum_label: FIELD_LABELS.BEHAVIORISM_TO_CONSTRUCTIVISM,
    reverse_scored: false,
    contributes_to_constructivism: true,
  },
  {
    id: 10,
    stem: "How often do you treat mistakes as data (predict → test → explain → revise), not as something to avoid quickly?",
    spectrum: "BEHAVIORISM_TO_CONSTRUCTIVISM",
    spectrum_label: FIELD_LABELS.BEHAVIORISM_TO_CONSTRUCTIVISM,
    reverse_scored: false,
    contributes_to_constructivism: true,
  },
  {
    id: 11,
    stem: "How often is “being correct on the first try” the main signal students receive that learning happened?",
    spectrum: "BEHAVIORISM_TO_CONSTRUCTIVISM",
    spectrum_label: FIELD_LABELS.BEHAVIORISM_TO_CONSTRUCTIVISM,
    reverse_scored: true,
    contributes_to_constructivism: false,
  },
  {
    id: 12,
    stem: "How often do students build understanding by connecting new ideas to prior experiences or examples they bring in?",
    spectrum: "BEHAVIORISM_TO_CONSTRUCTIVISM",
    spectrum_label: FIELD_LABELS.BEHAVIORISM_TO_CONSTRUCTIVISM,
    reverse_scored: false,
    contributes_to_constructivism: true,
  },
  {
    id: 13,
    stem: "How often do you structure discussion so students respond to each other with evidence (not just to you)?",
    spectrum: "COGNITIVISM_TO_SOCIAL_CONSTRUCTIVISM",
    spectrum_label: FIELD_LABELS.COGNITIVISM_TO_SOCIAL_CONSTRUCTIVISM,
    reverse_scored: false,
    contributes_to_constructivism: true,
  },
  {
    id: 14,
    stem: "How often do students use shared tools to co-construct meaning (e.g., shared notes, group models, joint solutions)?",
    spectrum: "COGNITIVISM_TO_SOCIAL_CONSTRUCTIVISM",
    spectrum_label: FIELD_LABELS.COGNITIVISM_TO_SOCIAL_CONSTRUCTIVISM,
    reverse_scored: false,
    contributes_to_constructivism: true,
  },
  {
    id: 15,
    stem: "How often is most thinking done silently and individually, with limited peer interaction during learning?",
    spectrum: "COGNITIVISM_TO_SOCIAL_CONSTRUCTIVISM",
    spectrum_label: FIELD_LABELS.COGNITIVISM_TO_SOCIAL_CONSTRUCTIVISM,
    reverse_scored: true,
    contributes_to_constructivism: false,
  },
  {
    id: 16,
    stem: "How often do students take roles that improve the quality of talk (summarizer, challenger, connector, evidence-checker)?",
    spectrum: "COGNITIVISM_TO_SOCIAL_CONSTRUCTIVISM",
    spectrum_label: FIELD_LABELS.COGNITIVISM_TO_SOCIAL_CONSTRUCTIVISM,
    reverse_scored: false,
    contributes_to_constructivism: false,
  },
  {
    id: 17,
    stem: "How often do students learn through authentic tasks (real audience, real data, real constraints) rather than only practice sets?",
    spectrum: "DIRECT_TO_EXPERIENTIAL",
    spectrum_label: FIELD_LABELS.DIRECT_TO_EXPERIENTIAL,
    reverse_scored: false,
    contributes_to_constructivism: true,
  },
  {
    id: 18,
    stem: "How often do you run “task first, mini-lesson after” so students notice patterns before you explain them?",
    spectrum: "DIRECT_TO_EXPERIENTIAL",
    spectrum_label: FIELD_LABELS.DIRECT_TO_EXPERIENTIAL,
    reverse_scored: false,
    contributes_to_constructivism: true,
  },
  {
    id: 19,
    stem: "How often is most class time spent on teacher explanation/modeling while students mainly listen or copy notes?",
    spectrum: "DIRECT_TO_EXPERIENTIAL",
    spectrum_label: FIELD_LABELS.DIRECT_TO_EXPERIENTIAL,
    reverse_scored: true,
    contributes_to_constructivism: false,
  },
  {
    id: 20,
    stem: "How often do students create a product or performance that requires applying learning in a new context?",
    spectrum: "DIRECT_TO_EXPERIENTIAL",
    spectrum_label: FIELD_LABELS.DIRECT_TO_EXPERIENTIAL,
    reverse_scored: false,
    contributes_to_constructivism: true,
  },
  {
    id: 21,
    stem: "How often do students use a rubric or success criteria they helped clarify (even if you drafted it first)?",
    spectrum: "CONSTRUCTIVISM_INDEX",
    spectrum_label: FIELD_LABELS.CONSTRUCTIVISM_INDEX,
    reverse_scored: false,
    contributes_to_constructivism: true,
  },
  {
    id: 22,
    stem: "How often do students generate questions that shape the lesson (what to investigate, what to test, what to read next)?",
    spectrum: "CONSTRUCTIVISM_INDEX",
    spectrum_label: FIELD_LABELS.CONSTRUCTIVISM_INDEX,
    reverse_scored: false,
    contributes_to_constructivism: true,
  },
  {
    id: 23,
    stem: "How often do students do short metacognitive routines (plan → monitor → reflect) during or after learning?",
    spectrum: "CONSTRUCTIVISM_INDEX",
    spectrum_label: FIELD_LABELS.CONSTRUCTIVISM_INDEX,
    reverse_scored: false,
    contributes_to_constructivism: true,
  },
  {
    id: 24,
    stem: "How often do students critique each other’s work using a protocol, then revise based on that critique?",
    spectrum: "CONSTRUCTIVISM_INDEX",
    spectrum_label: FIELD_LABELS.CONSTRUCTIVISM_INDEX,
    reverse_scored: false,
    contributes_to_constructivism: true,
  },
];
