#!/usr/bin/env python3
"""Generate corrected dreambeasts.json and full mindstream.json from Somnia 12 PDF."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "src" / "site" / "somnia" / "data"
EVENTS = ROOT / "src" / "site" / "somnia" / "data" / "event-landscapes.json"

# Suit pages: 12-14 Elasticity, 28-30 Lucidity, 44-46 Willpower (Somnia 12 print sheets)
DREAMBEASTS = [
    # Bosses (Dream deck)
    {"id": "cerberus", "name": "Cerberus", "suit": "willpower", "beastKind": "nightmare", "boss": True,
     "flavor": "Whom do you seek beyond my gate?", "accept": 12, "reject": 8, "repress": 8,
     "rejectSuit": "lucidity", "fail": "Repress top 4 Psyche",
     "effect": "Repress top 3 Psyche. Must play a Set (3 same # or suit).",
     "rejectReward": "Draw 3 Psyche.", "rejectEffect": {"type": "draw-psyche", "count": 3}},
    {"id": "double", "name": "Double", "suit": "elasticity", "beastKind": "nightmare", "boss": True,
     "flavor": "I'm just like you. But better.", "accept": 12, "reject": 7, "repress": 7,
     "rejectSuit": "lucidity", "fail": "Repress top 4 Psyche",
     "effect": "Forget Day in the Life & Naked Classroom. Must play a Pair.",
     "rejectReward": "Reveal 2 Landscapes.", "rejectEffect": {"type": "reveal-landscapes", "count": 2}},
    {"id": "leviathan", "name": "Leviathan", "suit": "lucidity", "beastKind": "nightmare", "boss": True,
     "flavor": "A terrible foe rises from the depths.", "accept": 12, "reject": 10, "repress": 10,
     "rejectSuit": "willpower", "fail": "Repress top 4 Psyche",
     "effect": "Forget 1 Landscape, Repress top 3 Psyche. Must play one of each suit (Balance).",
     "rejectReward": "Return 6 Psyche (Slumber).", "rejectEffect": {"type": "return-subconscious", "count": 1}},
    # Elasticity — pages 12-14
    {"id": "werewolf", "name": "Werewolf", "suit": "elasticity", "beastKind": "nightmare",
     "flavor": "You always were their favorite!!!", "accept": 10, "reject": 7, "repress": 7,
     "rejectSuit": "lucidity", "fail": "Repress 3 Psyche from hand",
     "effect": "Forget House & Suburbia.",
     "rejectReward": "Draw 2 Psyche.", "rejectEffect": {"type": "draw-psyche", "count": 2}},
    {"id": "bogey", "name": "Bogey", "suit": "elasticity", "beastKind": "nightmare",
     "flavor": "You're mine now!", "accept": 10, "reject": 6, "repress": 6,
     "rejectSuit": "lucidity", "fail": "Discard 1 Psyche, Repress 1 Psyche",
     "effect": "Repress top Psyche & 1 Elasticity Mindstream.",
     "rejectReward": "Draw 2 Objects.", "rejectEffect": {"type": "draw-object", "count": 2}},
    {"id": "mindless", "name": "Mindless", "suit": "elasticity", "beastKind": "nightmare",
     "flavor": "Arghhhh!", "accept": 11, "reject": 9, "repress": 9,
     "rejectSuit": "lucidity", "fail": "Forget 1 Landscape per Dreamer, Repress 1 Psyche per Dreamer",
     "effect": "Each Dreamer Repress 1 Psyche from Hand.",
     "rejectReward": "Return 1 Card.", "rejectEffect": {"type": "return-subconscious", "count": 1}},
    {"id": "automaton", "name": "Automaton", "suit": "elasticity", "beastKind": "nightmare",
     "flavor": "Where are you going? Where am I?", "accept": 8, "reject": 6, "repress": 6,
     "rejectSuit": "lucidity", "fail": "Discard a Power Token",
     "effect": "Move a Dreamer or Dreambeast 1 space.",
     "rejectReward": "Draw 1 Psyche.", "rejectEffect": {"type": "draw-psyche", "count": 1}},
    {"id": "guardian", "name": "Guardian", "suit": "elasticity", "beastKind": "nightmare",
     "flavor": "I command you advance no further.", "accept": 10, "reject": 7, "repress": 7,
     "rejectSuit": "lucidity", "fail": "Repress 2 Psyche from Hand",
     "effect": "Move all Dreamers 2 away from Bed.",
     "rejectReward": "Draw 4 Psyche.", "rejectEffect": {"type": "draw-psyche", "count": 4}},
    {"id": "merperson", "name": "Merperson", "suit": "elasticity", "beastKind": "fantasy",
     "flavor": "Sit, let me sing for you.", "accept": 7, "reject": 7, "repress": 7,
     "rejectSuit": "willpower", "fail": "Discard 3 Psyche",
     "effect": "Flip Leviathan. If Awake, move Leviathan to Endless Ocean.",
     "rejectReward": "Draw 2 Psyche.", "rejectEffect": {"type": "draw-psyche", "count": 2}},
    {"id": "trash-gremlin", "name": "Trash Gremlin", "suit": "elasticity", "beastKind": "fantasy",
     "flavor": "This is my trash! MINE!!!", "accept": 10, "reject": 6, "repress": 6,
     "rejectSuit": "lucidity", "fail": "Discard 2 Psyche",
     "effect": "Repress 1 Object from Hand.",
     "rejectReward": "Draw 2 Psyche.", "rejectEffect": {"type": "draw-psyche", "count": 2}},
    {"id": "nixie", "name": "Nixie", "suit": "elasticity", "beastKind": "fantasy",
     "flavor": "I can show you the way! Trust us.", "accept": 8, "reject": 6, "repress": 6,
     "rejectSuit": "willpower", "fail": "Discard 2 Psyche",
     "effect": "Forget Endless Ocean & Sea of Teeth.",
     "rejectReward": "Draw 2 Psyche.", "rejectEffect": {"type": "draw-psyche", "count": 2}},
    {"id": "jackalope", "name": "Jackalope", "suit": "elasticity", "beastKind": "fantasy",
     "flavor": "You trampled my flowers! Make more!", "accept": 8, "reject": 6, "repress": 6,
     "rejectSuit": "lucidity", "fail": "Discard 1 Psyche",
     "effect": "Repress top 3 Elasticity Mindstream.",
     "rejectReward": "Return 2 Repressed.", "rejectEffect": {"type": "return-subconscious", "count": 2}},
    {"id": "unicorn", "name": "Unicorn", "suit": "elasticity", "beastKind": "fantasy",
     "flavor": "Child of Light, join me on the path.", "accept": 7, "reject": 5, "repress": 5,
     "rejectSuit": "willpower", "fail": "Discard 3 Psyche",
     "effect": "Move Unicorn & Dreamer to any Landscape.",
     "rejectReward": "Return 2 Cards.", "rejectEffect": {"type": "return-subconscious", "count": 2}},
    # Lucidity — pages 28-30
    {"id": "black-dog", "name": "Black Dog", "suit": "lucidity", "beastKind": "nightmare",
     "flavor": "Ahooo!", "accept": 9, "reject": 7, "repress": 7,
     "rejectSuit": "willpower", "fail": "Repress 3 Psyche",
     "effect": "Lucidity 2: Draw 1 Psyche Card.",
     "rejectReward": "Draw 1 Object.", "rejectEffect": {"type": "draw-object", "count": 1}},
    {"id": "basilisk", "name": "Basilisk", "suit": "lucidity", "beastKind": "nightmare",
     "flavor": "Your friend is stone. You're next.", "accept": 9, "reject": 8, "repress": 8,
     "rejectSuit": "willpower", "fail": "Repress 3 Psyche",
     "effect": "Lucidity 1: Discard 2 Psyche Cards.",
     "rejectReward": "Draw 5 Psyche.", "rejectEffect": {"type": "draw-psyche", "count": 5}},
    {"id": "baku", "name": "Baku", "suit": "lucidity", "beastKind": "nightmare",
     "flavor": "Nom Nom Nom", "accept": 10, "reject": 8, "repress": 8,
     "rejectSuit": "willpower", "fail": "Repress 2 Psyche",
     "effect": "Forget Tranquil Grove and Awards.",
     "rejectReward": "Draw 1 Psyche, Return 1.", "rejectEffect": {"type": "draw-psyche", "count": 1}},
    {"id": "chimera", "name": "Chimera", "suit": "lucidity", "beastKind": "nightmare",
     "flavor": "No one escapes my wrath.", "accept": 9, "reject": 6, "repress": 6,
     "rejectSuit": "lucidity", "fail": "Repress top 3 Lucidity Mindstream",
     "effect": "Must use one Declared Card.",
     "rejectReward": "Return 1 Psyche.", "rejectEffect": {"type": "return-subconscious", "count": 1}},
    {"id": "gorgon", "name": "Gorgon", "suit": "lucidity", "beastKind": "nightmare",
     "flavor": "Come, behold my terrific beauty.", "accept": 6, "reject": 6, "repress": 6,
     "rejectSuit": "willpower", "fail": "Discard 1 Psyche",
     "effect": "Discard highest Psyche.",
     "rejectReward": "Draw 2 Power Tokens.", "rejectEffect": {"type": "gain-power", "count": 2}},
    {"id": "sandman", "name": "Sandman", "suit": "lucidity", "beastKind": "fantasy",
     "flavor": "Aren't you sleepy? Here, I'll help you.", "accept": 9, "reject": 8, "repress": 8,
     "rejectSuit": "willpower", "fail": "Each Dreamer Discard 2 Psyche",
     "effect": "Forget House & Road.",
     "rejectReward": "Cancel a Dream Draw, then Repress this card.", "rejectEffect": {"type": "draw-psyche", "count": 0}},
    {"id": "sincubus", "name": "Sincubus", "suit": "lucidity", "beastKind": "fantasy",
     "flavor": "Come here and give us a kiss.", "accept": 10, "reject": 5, "repress": 5,
     "rejectSuit": "lucidity", "fail": "Discard 4 Psyche",
     "effect": "Willpower 2 or less, Discard 2 Psyche Cards.",
     "rejectReward": "Draw 3 Psyche.", "rejectEffect": {"type": "draw-psyche", "count": 3}},
    {"id": "mandrake", "name": "Mandrake", "suit": "lucidity", "beastKind": "fantasy",
     "flavor": "Somebody help me!", "accept": 6, "reject": 6, "repress": 6,
     "rejectSuit": "willpower", "fail": "Discard 1 Psyche",
     "effect": "If Hand is 4 or less Repress 1 Psyche & 1 Object.",
     "rejectReward": "Draw 3 Psyche.", "rejectEffect": {"type": "draw-psyche", "count": 3}},
    {"id": "goofus-bird", "name": "Goofus Bird", "suit": "lucidity", "beastKind": "fantasy",
     "flavor": "This strange bird flies backwards.", "accept": 10, "reject": 6, "repress": 6,
     "rejectSuit": "willpower", "fail": "Discard 2 Psyche",
     "effect": "Repress 1 Lucidity Mindstream, Discard 1 Object.",
     "rejectReward": "Return 2 Repressed.", "rejectEffect": {"type": "return-subconscious", "count": 2}},
    {"id": "watcher", "name": "The Watcher", "suit": "lucidity", "beastKind": "fantasy",
     "flavor": "I have witnessed your waking world.", "accept": 9, "reject": 6, "repress": 6,
     "rejectSuit": "willpower", "fail": "Discard 2 Psyche",
     "effect": "Discard 1 Psyche Card per 2 Wastelands.",
     "rejectReward": "Reveal 2 Landscapes.", "rejectEffect": {"type": "reveal-landscapes", "count": 2}},
    # Willpower — pages 44-46
    {"id": "oni", "name": "Oni", "suit": "willpower", "beastKind": "nightmare",
     "flavor": "You killed my brother, prepare to die!", "accept": 10, "reject": 7, "repress": 7,
     "rejectSuit": "lucidity", "fail": "Repress 2 Psyche",
     "effect": "Repress top Willpower Mindstream & top 2 Psyche.",
     "rejectReward": "Draw 1 Object.", "rejectEffect": {"type": "draw-object", "count": 1}},
    {"id": "wendigo", "name": "Wendigo", "suit": "willpower", "beastKind": "nightmare",
     "flavor": "I'll eat you piece by piece!", "accept": 10, "reject": 7, "repress": 7,
     "rejectSuit": "lucidity", "fail": "Repress 2 Psyche",
     "effect": "Repress a Psyche card at least value 3 or else Repress 3.",
     "rejectReward": "Draw 2 Psyche or Objects.", "rejectEffect": {"type": "draw-psyche", "count": 2}},
    {"id": "minotaur", "name": "Minotaur", "suit": "willpower", "beastKind": "nightmare",
     "flavor": "You'll never leave my maze.", "accept": 10, "reject": 10, "repress": 10,
     "rejectSuit": "lucidity", "fail": "Repress 3 Psyche",
     "effect": "Forget Endless Hallway and Silver Mist.",
     "rejectReward": "Keep as if 1 Object of a set.", "rejectEffect": {"type": "gain-power", "count": 1}},
    {"id": "ghost-light", "name": "Ghost Light", "suit": "willpower", "beastKind": "nightmare",
     "flavor": "Why didn't you save me?", "accept": 10, "reject": 8, "repress": 8,
     "rejectSuit": "willpower", "fail": "Repress 3 Psyche",
     "effect": "Repress top Willpower Mindstream.",
     "rejectReward": "Draw 1 Object & 1 Psyche.", "rejectEffect": {"type": "draw-object", "count": 1}},
    {"id": "vampyre", "name": "Vampyre", "suit": "willpower", "beastKind": "nightmare",
     "flavor": "Come to me, let me embrace you.", "accept": 10, "reject": 8, "repress": 8,
     "rejectSuit": "lucidity", "fail": "Discard 3 Psyche",
     "effect": "Discard Psyche Cards = half Dreamers.",
     "rejectReward": "Draw 1 Set Object.", "rejectEffect": {"type": "draw-object", "count": 1}},
    {"id": "pooka", "name": "Pooka", "suit": "willpower", "beastKind": "fantasy",
     "flavor": "What have you got to trade?", "accept": 8, "reject": 6, "repress": 6,
     "rejectSuit": "willpower", "fail": "Discard 2 Psyche",
     "effect": "Repress top Willpower Mindstream.",
     "rejectReward": "Draw 2 Objects.", "rejectEffect": {"type": "draw-object", "count": 2}},
    {"id": "shadows", "name": "Shadows", "suit": "willpower", "beastKind": "fantasy",
     "flavor": "We've been following. Now we lead.", "accept": 7, "reject": 5, "repress": 5,
     "rejectSuit": "lucidity", "fail": "Discard 1 Psyche",
     "effect": "Forget City and Forest.",
     "rejectReward": "Reveal 3 Landscapes.", "rejectEffect": {"type": "reveal-landscapes", "count": 3}},
    {"id": "cheshire-cat", "name": "Cheshire Cat", "suit": "willpower", "beastKind": "fantasy",
     "flavor": "We're all mad here.", "accept": 9, "reject": 7, "repress": 7,
     "rejectSuit": "willpower", "fail": "Discard 2 Psyche",
     "effect": "Repress top 2 Psyche Cards.",
     "rejectReward": "Reveal 3 Landscapes.", "rejectEffect": {"type": "reveal-landscapes", "count": 3}},
    {"id": "masked-figure", "name": "Masked Figure", "suit": "willpower", "beastKind": "fantasy",
     "flavor": "Lose yourself to find your Self.", "accept": 10, "reject": 6, "repress": 6,
     "rejectSuit": "lucidity", "fail": "Discard 3 Psyche",
     "effect": "Forget Inner Sanctum and The Party.",
     "rejectReward": "Draw 2 Objects.", "rejectEffect": {"type": "draw-object", "count": 2}},
    {"id": "winged-turtle", "name": "Winged Turtle", "suit": "willpower", "beastKind": "fantasy",
     "flavor": "Where there's wings, there's a way.", "accept": 9, "reject": 7, "repress": 7,
     "rejectSuit": "willpower", "fail": "Discard 2 Psyche",
     "effect": "Repress 3 - Willpower Psyche Cards.",
     "rejectReward": "Reveal 3 Landscapes.", "rejectEffect": {"type": "reveal-landscapes", "count": 3}},
]

IMAGE = "images/dreambeasts/{id}.webp"

def event(suit, id_, name, text):
    slug = id_
    return {
        "id": slug,
        "name": name,
        "suit": suit,
        "type": "event",
        "image": f"images/cards/mindstream/{suit}/{slug}.webp",
        "text": text,
    }

LUCIDITY_EVENTS = [
    event("lucidity", "fantastic-imagination", "Fantastic Imagination", "Reveal 1 Landscape. If Lucidity 0-2, Reveal +1. If Lucidity 3+, Return 3 Cards."),
    event("lucidity", "centering", "Centering", "Draw 2 Psyche. All Dreamers Draw 1 Psyche & 1 Power Token. Then Move to an adjacent Landscape."),
    event("lucidity", "the-ascent", "The Ascent", "Discard your highest Psyche, then Draw 2 Psyche. Dreamers on Affected Landscapes may also use this effect."),
    event("lucidity", "beyond-comprehension", "Beyond Comprehension", "Flip Leviathan. Instead, Forget 4 Landscapes. Return 4 cards."),
    event("lucidity", "just-a-dream", "Just a Dream", "Draw 3 Psyche. Return 1 Card for each Affected Landscape."),
    event("lucidity", "morning-routine", "Morning Routine", "Draw 1 Psyche. Draw Psyche up to Landscapes Affected. Repress top 1 Lucidity Mindstream card."),
    event("lucidity", "afternoon-nap", "Afternoon Nap", "Draw 1 Psyche. If less than your Lucidity, Return cards up to your Lucidity. Keep Psyche."),
    event("lucidity", "evening-plans", "Evening Plans", "Draw 1 Psyche OR flip top of 1 Deck. Draw 2 Lucidity Encounters and place on Landscapes adjacent to Day in the Life."),
    event("lucidity", "i-know-this-place", "I Know This Place!", "Return 1 Card. Return +Dreamers Cards."),
    event("lucidity", "im-still-dreaming", "I'm Still Dreaming", "Discard 2 Psyche. Move to Insanity or Day in the Life."),
    event("lucidity", "a-way-out-forms", "A Way Out Forms", "Discard 1 Psyche. May Discard Psyche up to Landscapes Affected to flip top cards of any deck."),
    event("lucidity", "voice-in-the-distance", "Voice in the Distance", "Take 1 Power Token. Move to Road or Endless Hallway."),
    event("lucidity", "somethings-over-there", "Something's Over There", "May Discard 1 Psyche to Draw a Dreambeast and place on any Landscape. Instead, Draw 2 Encounters, Choose 1."),
    event("lucidity", "a-face-appears", "A Face Appears", "Spawn 1 Encounter from Lucidity Mindstream. If Lucidity 3+, Return 3 Cards."),
    event("lucidity", "mist-swirls", "Mist Swirls", "Discard 1 Dream. If Lucidity 3+, Discard 1 Psyche to Reveal Persona+1 Landscapes."),
    event("lucidity", "transported", "Transported", "Draw 2 Psyche. 1st is column, 2nd is row of Dreamscape. Move to this Landscape."),
    event("lucidity", "lightness", "Lightness", "Draw 2 Psyche. Discard 1 Psyche; all Dreamers may Draw Psyche up to the value of the card."),
    event("lucidity", "the-council-of-the-years", "The Council of The Years", "Draw 4 Psyche, Repress 3, keep 1. Instead, Draw 4 Dreambeasts, Repress 3, Meet 1 now."),
    event("lucidity", "sublimation", "Sublimation", "Discard 1 Psyche to Return 1 Card and take 1 Power Token. Discard up to 4 Psyche to Return up to 4 cards from the Subconscious."),
    event("lucidity", "serenity", "Serenity", "Draw +3 Psyche. Take 1 Power Token. Move to The Party or Day in the Life."),
    event("lucidity", "harmonic-resonance", "Harmonic Resonance", "If Lucidity 1, Draw 1 Psyche. If Lucidity 3+, Return 2 Cards. Draw +1 Psyche or Return +2."),
    event("lucidity", "denial", "Denial", "Return 4 Cards. If Lucidity 3+, Return +Dreamers."),
    event("lucidity", "keep-it-together", "Keep it Together", "Repress Objects from hand unless you Discard Psyche equal to the number of Objects you wish to spare."),
    event("lucidity", "metamorphosis", "Metamorphosis", "Repress Active Encounters+2 top Psyche. Forget 2 Landscapes per Affected Landscape."),
    event("lucidity", "contagion", "Contagion", "Repress top 2 Psyche. Lucidity 2 or less, Repress +1 per Affected Landscape."),
    event("lucidity", "forgot-clothes", "Forgot Clothes", "Repress 1 Psyche from hand. If Lucidity 1-2, Move adjacent. If Lucidity 3+, Move anywhere."),
    event("lucidity", "wrong-classroom", "Wrong Classroom", "Repress top of Lucidity Mindstream. Discard Active Encounters+1 Psyche from hand."),
    event("lucidity", "everyones-laughing", "Everyone's Laughing", "Discard 2 Objects. Lucidity 3+, Instead Discard 1 Psyche. Discard Psyche equal to half Active Encounters (min 1)."),
    event("lucidity", "pop-quiz", "Pop Quiz", "Draw 1 Psyche. Guess if next Psyche is Higher or Lower. Correct: Return Dreamers+3."),
    event("lucidity", "revolving", "Revolving", "Draw 3 Psyche. Repress 1 Psyche from hand. Swap Positions with any other Dreamer."),
    event("lucidity", "blooming", "Blooming", "Swap Positions of any 4 unoccupied Landscape Hexes. Repress 1 Psyche from hand."),
    event("lucidity", "break-out", "Break-out", "Discard 1 Psyche. Draw 1 Psyche. If it matches a Psyche in your hand, Return 4 Cards."),
    event("lucidity", "sacred-geometry", "Sacred Geometry", "Move to any Landscape adjacent to Bed. Return 2 Cards per Affected Landscape."),
    event("lucidity", "caught-cheating", "Caught Cheating", "Discard 1 Psyche. Draw 1 Psyche. If it matches hand, Return 4 Cards; if not, discard 1 Psyche."),
    event("lucidity", "feel-deal-heal", "Feel, Deal, Heal", "Flip Leviathan. Discard your lowest Psyche, shuffle Psyche Discard into Deck, Draw 1 Psyche. Draw +1 per Affected Landscape."),
]

ELASTICITY_EVENTS = [
    event("elasticity", "a-shining-wind", "A Shining Wind", "If Elasticity 3+, take 2 Power Tokens. Move to Silver Mist or Endless Ocean."),
    event("elasticity", "a-million-reflections", "A Million Reflections", "Repress choice of 4 Discarded Mindstream Cards. Return 4 Cards."),
    event("elasticity", "this-will-have-to-do", "This Will Have to Do", "May Discard 1 Psyche less than or equal to your Elasticity to Draw 2 Psyche."),
    event("elasticity", "is-that-music", "Is That Music?", "Discard 1 Psyche to Draw 1 Psyche. Elasticity 3+, Take 1 Power Token and Move to Awards or The Party."),
    event("elasticity", "roof-dive", "Roof Dive", "Elasticity 3+, Move to Sky, The Party, or Candy Mountain."),
    event("elasticity", "cotton-candy", "Cotton Candy", "May Discard 1 Psyche to Draw Psyche up to value. Move to Candy Mountain Refreshed! Draw 3 Psyche."),
    event("elasticity", "insulation", "Insulation", "Keep this card. Next Explore, Move+1. Then Discard this card."),
    event("elasticity", "shimmering-slivers", "Shimmering Slivers", "Draw 1 Object. Draw 1 Psyche for each Affected Landscape."),
    event("elasticity", "diamonds", "Diamonds", "Discard 1 Psyche to Draw 1 Psyche and Return 4 Cards from Subconscious and Take 1 Power Token."),
    event("elasticity", "desert-oasis", "Desert Oasis", "Draw 3 Psyche and Take 1 Power Token. Move to House or Suburbia."),
    event("elasticity", "need-water", "Need Water!", "Discard 1 Psyche. Discard 1 Willpower Psyche or Discard all Objects."),
    event("elasticity", "into-the-next", "Into The Next", "All Dreamers Draw 1 Psyche. Repress top 1 Elasticity Mindstream. Move to adjacent Landscape & take a free Action."),
    event("elasticity", "broken-toys", "Broken Toys", "Discard 2 Psyche. Draw 2 Psyche."),
    event("elasticity", "flooded", "Flooded", "Elasticity 1-2, Move to Endless Ocean. Elasticity 3+, Move to House or Suburbia."),
    event("elasticity", "running-somewhere", "Running Somewhere?", "Draw 1 Psyche. Elasticity 3+, May Discard 1 Psyche to Return cards equal to value."),
    event("elasticity", "portal-another-world", "Portal to Another World", "Elasticity 0-2 Move 1. Elasticity 3+ Move 3. Move to edge of Dreamscape."),
    event("elasticity", "giant-animated-pile", "Giant Animated Pile", "Draw 1 Dreambeast, Meet Now at half Accept & Repress cost."),
    event("elasticity", "dust-bunnies", "Dust Bunnies", "Draw 1 Dreambeast. Repress this Dreambeast & 1 Psyche. Draw 1 Object."),
    event("elasticity", "lost-treasure", "Lost Treasure", "Elasticity 0-2, Discard 1 Psyche. Elasticity 3+, Draw 3 Psyche. Return 1 Card per Affected Landscape."),
    event("elasticity", "wrong-door", "Wrong Door", "Return 2 Dreambeasts from Accept Pile and Spawn on adjacent Landscapes. If can't, Discard 4 Psyche."),
    event("elasticity", "hidden-in-the-walls", "Hidden in the Walls", "Draw 1 Psyche. Draw 1 Dreambeast: Draw 5 Psyche, Meet Now, Fail cost doubled."),
    event("elasticity", "deeper-darker", "Deeper Darker", "Elasticity 1-2, Discard 1 Psyche. Elasticity 3+, Draw 1 Object. If all Affected Landscapes Revealed, All Dreamers Draw 2 Psyche."),
    event("elasticity", "undulating-floor", "Undulating Floor", "Move to Any Landscape. Place 1 Power Token on an available Archetype."),
    event("elasticity", "the-right-door", "The Right Door", "Elasticity 0-2, Discard 1 Psyche. Elasticity 3+, Draw 3 Psyche."),
    event("elasticity", "just-out-of-reach", "Just out of Reach", "Elasticity 3+, Discard 1 Psyche to Return cards up to Affected Landscapes."),
    event("elasticity", "splinters", "Splinters", "Draw 2 Dreambeasts. Spawn 1 on Endless Hallway and 1 on Attic. If not, Discard 2 Psyche."),
    event("elasticity", "freezing-night", "Freezing Night", "Elasticity 0-2, Draw 2 Psyche keep 1. Willpower 3+, Draw 2 Objects keep 1."),
    event("elasticity", "searing-day", "Searing Day", "Elasticity 0-2, Discard 2 Psyche. Elasticity 3+, Draw 2 Psyche."),
    event("elasticity", "a-mirage", "A Mirage?", "Spawn 1 Dreambeast, pay Fail cost first then resolve."),
    event("elasticity", "sandstorm", "Sandstorm!", "Elasticity 0-2, Discard 1 Object or Psyche. Elasticity 3+, Move to Tranquil Grove or Inner Sanctum."),
    event("elasticity", "friendship", "Friendship", "Reveal 2 Landscapes. Move to either. Elasticity 3+, 1 Free Action."),
    event("elasticity", "get-up", "Get Up", "Draw 1 Psyche from Discard. May Move to Forest if Revealed. Move to Attic and take free Meet."),
    event("elasticity", "get-down", "Get Down", "Draw 1 Psyche from Discard. May Move to City if Revealed. Move to Basement and take free Meet."),
    event("elasticity", "bronze", "Bronze", "Return 2 Dreambeasts from Accept Pile. Spawn 1 Dreambeast on any Affected Landscape."),
    event("elasticity", "silver", "Silver", "Spawn 1 Dreambeast. Accept 1 Dreambeast on any Affected Landscape."),
    event("elasticity", "gold", "Gold", "Return 3 Dreambeasts from Accept Pile. Draw 1 Object. Elasticity 3+, Draw +1 Object."),
]

WILLPOWER_EVENTS = [
    event("willpower", "a-thousand-daggers", "A Thousand Daggers", "All Dreamers collectively Repress Dreamers+2 Psyche from hand."),
    event("willpower", "flashing-lights", "Flashing Lights", "Draw 2 Psyche. Take 2 Power Tokens."),
    event("willpower", "rhythm-of-the-night", "Rhythm of the Night", "May Discard 1 Object for all Dreamers to Draw 2 Psyche."),
    event("willpower", "roiling-doom", "Roiling Doom", "Discard 2 Psyche. Draw 2 Encounters, Immediately Meet 1, Discard other."),
    event("willpower", "perilous-pinnacle", "Perilous Pinnacle", "Discard 2 Objects. Meet both Encounters in order of your choice."),
    event("willpower", "cooling-obsidian", "Cooling Obsidian", "Repress 1 Active Encounter. Move to Endless Ocean or Field of Broken Glass."),
    event("willpower", "from-the-fire", "From the Fire", "Return 2 Repressed Encounters. Return +2 Cards."),
    event("willpower", "a-sacrifice", "A Sacrifice!", "Discard 1 Object to Return Dreamers+1 Objects. Repress Encounters on Affected Landscapes."),
    event("willpower", "heating-up", "Heating Up", "Spawn 1 Encounter, Meet it. If Accept spawn another; if Repress Draw Psyche up to hand limit."),
    event("willpower", "no-thing", "No Thing", "Discard 3 Dream Cards. Willpower 3+, Return 1 Dream card to deck and shuffle."),
    event("willpower", "no-time", "No Time", "Collectively Discard 1 Object per Dreamer. May Repress 4 Mindstream to ignore."),
    event("willpower", "no-where", "No Where", "Forget 4 Landscapes. Repress top 1 Psyche from Psyche deck. Draw 2 Psyche for grid move without Meet."),
    event("willpower", "choppy-water", "Choppy Water", "Discard 1 Willpower Psyche to Draw 1 Psyche and Return 4 Cards."),
    event("willpower", "big-wave", "Big Wave", "Draw 1 Psyche. May Discard 1 Higher Value Psyche to Return 3 Cards."),
    event("willpower", "fog", "Fog", "Discard 1 Willpower Psyche to Draw 2 Psyche. Move to Silver Mist."),
    event("willpower", "clear-as-crystal", "Clear as Crystal", "Willpower 2 or less: Draw 3 Psyche. Willpower 3+: Draw 3 Psyche and Return 2."),
    event("willpower", "a-mouth-rises", "A Mouth Rises", "Flip Leviathan. If Awake, Move it to Endless Ocean."),
    event("willpower", "whirlpool", "Whirlpool", "Willpower 1-2, Flip Leviathan. Willpower 3+, Move 2 toward Endless Ocean."),
    event("willpower", "syrup-lake", "Syrup Lake", "Take 1 Power Token. Draw 1 Psyche. Move to Candy Mountain."),
    event("willpower", "peppermint-peak", "Peppermint Peak", "Discard 1 Willpower Psyche up to your Willpower to Draw 3 Psyche."),
    event("willpower", "licorice-bridge", "Licorice Bridge", "Draw 1 Psyche and skip your next Explore phase."),
    event("willpower", "chocolate-mines", "Chocolate Mines", "Draw 1 Psyche. Draw +2 Psyche for each Affected Landscape."),
    event("willpower", "marshmallow-clouds", "Marshmallow Clouds", "Take 2 Power Tokens. May Draw 1 any Mindstream. All Dreamers Take 1 Power Token."),
    event("willpower", "jaw-shark", "Jaw Shark", "Discard 2 Willpower Psyche or else Repress 2 Psyche from hand. If unable, Discard all Objects."),
    event("willpower", "ivory-calm", "Ivory Calm", "Willpower 1-2: Draw 1 Psyche. Willpower 3+, Draw 1 Psyche and Return 3."),
    event("willpower", "tartar-algae", "Tartar Algae", "Draw +1 Psyche and Return +1 for Each Affected Landscape."),
    event("willpower", "caramel-forest", "Caramel Forest", "Draw 2 Encounters. Spawn 1 on Adjacent Landscape. Discard other."),
    event("willpower", "chewed-to-dust", "Chewed to Dust", "Repress top of Each Mindstream. Discard 3 Psyche or else Discard 1 Dream."),
    event("willpower", "gap-in-the-teeth", "Gap in the Teeth", "Draw 2 Psyche. Move to Candy Mountain or Endless Ocean."),
    event("willpower", "golden-tooth", "Golden Tooth", "Willpower 1-2: Draw 2 Psyche. Willpower 3+: Draw 1 Object from any Mindstream."),
    event("willpower", "who-is-there", "Who's There?", "Spawn an Encounter and Meet Now. Instead, Draw 2 Encounters, Pick 1. Repress top 1 Willpower Mindstream card."),
    event("willpower", "no-why", "No Why", "Draw from any Mindstream. All Dreamers may each Draw from any Mindstream."),
    event("willpower", "no-one", "No One", "Discard all active Encounters. Willpower 3+, Instead Discard 1 Encounter."),
    event("willpower", "i-remember", "I Remember!", "May Discard 1 Psyche up to your Willpower to Return 1 Card. Return +Cards equal to your Willpower."),
    event("willpower", "dream-for-landscapes", "Dream Toll", "Discard 1 Dream for Each Affected Landscape."),
]

MINDSTREAM = {
    "lucidity": LUCIDITY_EVENTS[:35],
    "elasticity": ELASTICITY_EVENTS[:35],
    "willpower": WILLPOWER_EVENTS[:35],
}


def main():
    beasts_out = []
    for b in DREAMBEASTS:
        beasts_out.append({
            **b,
            "type": "dreambeast",
            "image": IMAGE.format(id=b["id"]),
        })
    (DATA / "dreambeasts.json").write_text(
        json.dumps(beasts_out, indent=2) + "\n", encoding="utf-8"
    )

    (DATA / "mindstream.json").write_text(
        json.dumps(MINDSTREAM, indent=2) + "\n", encoding="utf-8"
    )

    # Extend event-landscapes with generic entries for new events
    existing = {}
    if EVENTS.exists():
        existing = json.loads(EVENTS.read_text(encoding="utf-8"))
    generic = ["forest", "road", "house", "city", "sky", "awards", "tranquil-grove", "silver-mist"]
    for suit, events in MINDSTREAM.items():
        for e in events:
            if e["id"] not in existing:
                existing[e["id"]] = {
                    "landscapes": generic,
                    "effectTop": e["text"],
                }
    EVENTS.write_text(json.dumps(existing, indent=2) + "\n", encoding="utf-8")

    print(f"Wrote {len(beasts_out)} dreambeasts")
    for suit, evs in MINDSTREAM.items():
        print(f"  {suit}: {len(evs)} mindstream events")


if __name__ == "__main__":
    main()
